type ArchitectureProps = {
  architecture: {
    frontend: string;
    backend: string;
    database: string;
  };
};

export default function Architecture({
  architecture,
}: ArchitectureProps) {
  const items = [
    {
      title: "Frontend",
      value: architecture.frontend,
    },
    {
      title: "Backend",
      value: architecture.backend,
    },
    {
      title: "Database",
      value: architecture.database,
    },
  ];

  return (
    <div className="rounded-2xl border border-[#27272A] bg-[#18181B] p-5">

      <h2 className="text-xl font-semibold">
        Architecture
      </h2>

      <p className="mt-2 text-sm text-[#A1A1AA]">
        High level system architecture generated by AI.
      </p>

      <div className="mt-5 grid gap-4 md:grid-cols-3">

        {items.map((item) => (
          <div
            key={item.title}
            className="
              rounded-xl
              border
              border-[#27272A]
              bg-[#09090B]
              p-4
              transition
              hover:border-[#52525B]
            "
          >
            <h3 className="text-sm font-medium text-[#FAFAFA]">
              {item.title}
            </h3>

            <p className="mt-3 text-sm leading-6 text-[#A1A1AA]">
              {item.value}
            </p>
          </div>
        ))}

      </div>

    </div>
  );
}
