import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { oneDark } from "react-syntax-highlighter/dist/esm/styles/prism";

type FolderStructureProps = {
  folderStructure: Record<string, any>;
};

function buildTree(
  obj: Record<string, any>,
  prefix = ""
): string[] {
  const lines: string[] = [];

  const entries = Object.entries(obj);

  entries.forEach(([key, value], index) => {
    const isLast = index === entries.length - 1;

    const connector = isLast ? "└── " : "├── ";

    lines.push(`${prefix}${connector}${key}`);

    if (
      value &&
      typeof value === "object" &&
      !Array.isArray(value)
    ) {
      lines.push(
        ...buildTree(
          value,
          `${prefix}${isLast ? "    " : "│   "}`
        )
      );
    }

    if (Array.isArray(value)) {
      value.forEach((item, childIndex) => {
        const childLast =
          childIndex === value.length - 1;

        lines.push(
          `${prefix}${isLast ? "    " : "│   "}${
            childLast ? "└── " : "├── "
          }${item}`
        );
      });
    }
  });

  return lines;
}

export default function FolderStructure({
  folderStructure,
}: FolderStructureProps) {
  const treeText = buildTree(folderStructure).join("\n");

  return (
    <div className="rounded-2xl border border-[#27272A] bg-[#18181B] p-5">

      <h2 className="text-xl font-semibold">
        Folder Structure
      </h2>

      <p className="mt-2 text-sm text-[#A1A1AA]">
        Recommended project structure generated by AI.
      </p>

      <div
        className="
          mt-5
          overflow-x-auto
          rounded-xl
          border
          border-[#27272A]
        "
      >
        <SyntaxHighlighter
          language="text"
          style={oneDark}
          wrapLongLines={false}
          customStyle={{
            margin: 0,
            background: "#09090B",
            padding: "20px",
            fontSize: "13px",
            minWidth: "100%",
          }}
        >
          {treeText}
        </SyntaxHighlighter>
      </div>

    </div>
  );
}