type RoadmapPhase = {
  phase: string;
  tasks: string[];
};

type RoadmapSectionProps = {
  roadmap: RoadmapPhase[];
};

export default function Roadmap({
  roadmap,
}: RoadmapSectionProps) {
  return (
    <div className="rounded-2xl border border-[#27272A] bg-[#18181B] p-5">

      <h2 className="text-xl font-semibold">
        Development Roadmap
      </h2>

      <p className="mt-2 text-sm text-[#A1A1AA]">
        Recommended implementation phases generated by AI.
      </p>

      <div className="mt-6">

        {roadmap.map((phase, index) => (
          <div
            key={phase.phase}
            className="relative flex gap-4 pb-8 last:pb-0"
          >
            {/* Timeline */}

            <div className="flex flex-col items-center">

              <div
                className="
                  h-4
                  w-4
                  rounded-full
                  bg-[#E4E4E7]
                "
              />

              {index !== roadmap.length - 1 && (
                <div
                  className="
                    mt-2
                    h-full
                    w-[2px]
                    bg-[#27272A]
                  "
                />
              )}

            </div>

            {/* Content */}

            <div
              className="
                flex-1
                rounded-xl
                border
                border-[#27272A]
                bg-[#09090B]
                p-4
                transition
                hover:border-[#52525B]
              "
            >
              <h3 className="text-base font-medium">
                {phase.phase}
              </h3>

              <div className="mt-3 space-y-2">

                {phase.tasks.map((task) => (
                  <div
                    key={task}
                    className="text-sm text-[#A1A1AA]"
                  >
                    • {task}
                  </div>
                ))}

              </div>

            </div>

          </div>
        ))}

      </div>

    </div>
  );
}
